### ISSUE TITLE
how to run the site

### ISSUE THREAD

**Issue by alaniskhan** [FTW-Entertainment-LLC/AnimeFTW.tv-Site#324]
How can I run the site

**Comment by robotman321** [comment]
@alaniskhan this repo was never intended to be a drop-in solution for a variety of reasons,

1. This codebase was designed for php 5.6 and has no testing on 7+
2. Mysql schema was omitted 

I encourage you to use the code base as a reference for any projects you may want to do. As well, the v6 code base has much more modern authentication setup which is much more secure.
